services:
  postgres:
    image: postgres
    # restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: nextmatch
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432
